tests: decode binary url in _ReleaseTestResource for py3
On Python 3, this test fails:

  builtins.TypeError: a bytes-like object is required, not 'str'